import {
    DEFAULT_DIMENSIONS,
    DEFAULT_LEG_DIMENSIONS,
    DEFAULT_BODY_DIMENSIONS,
    DEFAULT_POSE,
    DEFAULT_PATTERN_PARAMS,
    DEFAULT_IK_PARAMS,
    DEFAULT_GAIT_PARAMS,
} from "./hexapodParams"

import { DATA, LAYOUT, DATA_INDEX_MAP, SCENE, CAMERA_VIEW } from "./plotParams"
import { VirtualHexapod } from "../hexapod"

const VIRTUAL_HEXAPOD = new VirtualHexapod(DEFAULT_DIMENSIONS, DEFAULT_POSE)

export {
    VIRTUAL_HEXAPOD,
    DEFAULT_DIMENSIONS,
    DEFAULT_LEG_DIMENSIONS,
    DEFAULT_BODY_DIMENSIONS,
    DEFAULT_POSE,
    DEFAULT_PATTERN_PARAMS,
    DEFAULT_GAIT_PARAMS,
    DEFAULT_IK_PARAMS,
    DATA,
    LAYOUT,
    DATA_INDEX_MAP,
    SCENE,
    CAMERA_VIEW,
}
